const vocabularyData = {
    jobHunt: [
        {en: "an application", fr: "une candidature"},
        {en: "to apply for", fr: "poser une candidature pour"},
        {en: "an applicant / a candidate", fr: "un(e) candidat(e)"},
        {en: "classified ads", fr: "les petites annonces"},
        {en: "a cover letter / an application letter", fr: "une lettre de motivation"},
        {en: "a CV / a résumé", fr: "un CV"},
        {en: "to be unemployed / jobless / out of work", fr: "être au chômage, sans emploi"},
        {en: "a job-seeker", fr: "un demandeur d'emploi"},
        {en: "to be on the dole", fr: "vivre des allocations chômage"},
        {en: "to get employed", fr: "être engagé(e)"},
        {en: "to enter the working world", fr: "entrer dans le monde professionnel"},
        {en: "qualifications", fr: "diplômes, qualifications"},
        {en: "a diploma", fr: "un diplôme"},
        {en: "an endorsement / a recommendation", fr: "un soutien à un candidat, une recommandation"},
        {en: "a graduate", fr: "un diplômé"},
        {en: "a qualification", fr: "une qualification, une expérience"},
        {en: "proficiency (in) / skills (in)", fr: "aptitude, compétences dans un registre"},
        {en: "to be experienced", fr: "avoir de l'expérience"},
        {en: "to be qualified for a job", fr: "avoir l'expérience requise et les diplômes pour un travail"},
        {en: "to graduate / to be graduated from", fr: "obtenir une licence / être diplômé(e) de"},
        {en: "to have work experience / professional experience", fr: "avoir de l'expérience professionnelle"},
        {en: "social media", fr: "réseaux sociaux"},
        {en: "to be careful to ≠ not to", fr: "veiller à ≠ à ne pas"},
        {en: "to be effective / to be working", fr: "être efficace, être travailleur(-se)"},
        {en: "to be time-saving", fr: "qui fait gagner du temps"},
        {en: "to make something easier / to facilitate", fr: "faciliter quelque chose"},
        {en: "to run a risk", fr: "courir un risque"},
        {en: "to take precautions", fr: "prendre des précautions"},
        {en: "to coach somebody", fr: "montrer à quelqu'un comment faire quelque chose"},
        {en: "to be coached (in something)", fr: "être entraîné(e) à faire quelque chose"},
        {en: "a career adviser", fr: "un conseiller carrière"},
        {en: "a coach", fr: "un entraîneur"},
        {en: "to benefit from (somebody's advice)", fr: "bénéficier des conseils de quelqu'un"},
        {en: "to resort to / to use", fr: "avoir recours à / utiliser"},
        {en: "to take (someone's advice) into account", fr: "prendre en compte les conseils de quelqu'un"},
        {en: "to speak about one's personality", fr: "parler de sa personnalité"},
        {en: "to be trustworthy", fr: "être digne de confiance"},
        {en: "to have qualities ≠ faults", fr: "avoir des qualités ≠ des défauts"},
        {en: "to promote oneself", fr: "se vendre, mettre en avant ses qualités"}
    ],
    
    cybersecurity: [
        {en: "computer hackers", fr: "les pirates informatiques"},
        {en: "to click on a link", fr: "cliquer sur un lien"},
        {en: "an attachment", fr: "un fichier joint"},
        {en: "to infect a computer", fr: "infecter un ordinateur"},
        {en: "to access data", fr: "avoir accès aux données"},
        {en: "bank details", fr: "les coordonnées bancaires"},
        {en: "to install an antivirus software", fr: "installer un antivirus"},
        {en: "to block out viruses", fr: "bloquer les virus"},
        {en: "to update", fr: "mettre à jour"},
        {en: "fraudulent", fr: "frauduleux"},
        {en: "suspicious", fr: "douteux"},
        {en: "fake", fr: "faux"},
        {en: "malicious", fr: "malveillant"},
        {en: "a hoax", fr: "un canular"},
        {en: "to back up", fr: "sauvegarder"},
        {en: "protection levels", fr: "les niveaux de protection"},
        {en: "firewall", fr: "pare-feu"},
        {en: "IP address", fr: "adresse IP"},
        {en: "Trojan horse", fr: "cheval de Troie"},
        {en: "phishing", fr: "hameçonnage"},
        {en: "data breach", fr: "violation de données / fuite de données"},
        {en: "data theft", fr: "vol de données"},
        {en: "authentication", fr: "authentification"},
        {en: "multi-factor authentication / 2FA", fr: "authentification à multifacteurs"},
        {en: "CAPTCHA", fr: "authentification par question-réponse"},
        {en: "backdoor", fr: "porte dérobée"},
        {en: "botnet attack", fr: "attaque par réseau de (ro)bots"},
        {en: "large-scale attack", fr: "attaque de grande ampleur"},
        {en: "brute force attack", fr: "attaque par force brute"},
        {en: "blacklist", fr: "liste noire"},
        {en: "classified information", fr: "information classée secrète"},
        {en: "cyber spying", fr: "cyberespionnage"},
        {en: "hacker", fr: "pirate (informatique)"},
        {en: "hacking", fr: "piratage"},
        {en: "to hack", fr: "pirater"}
    ],
    
    // Le mix automatique
    get mix() {
        return [...this.jobHunt, ...this.cybersecurity];
    }
};